version: '3.8'
services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: article
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    depends_on:
      - mysql
    environment:
      DB_USER: root
      DB_PASS: password
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: article
      PORT: 8080
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE: http://backend:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql_data:
